# Change Ctrl-B binding to Ctrl-A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix # still send the raw key to other processes 

# Allow resizing and selecting windows with the mouse
set -g mouse on

# Switch terminal windows with vim movement keys;
# Don't require prefix to do so
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable Vi mode
set-window-option -g mode-keys vi

# Use the current directory for new panes/windows
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

